import tkinter as tk

BUTTON_FONT = ("Lora", 16)
BUTTON_WIDTH = 20
BUTTON_COLOR = "#F76902"
BACK_TO_MENU_FONT = ("LATO", 10)
ACTIVE_BUTTON_COLOR = "#D35400"

TITLE_FONT = ("LATO", 20)
SUBTITLE_FONT = ("LATO", 16)
BACKGROUND_COLOR = "#3A3A3A"

